app/models/character.py
import datetime

class Character():
    def __init__(self, _id, name, alive, species, typo, gender, origin, location_name, episode, image_url, created, episode_n):
        self._id = _id
        self.name = name
        self.alive = alive
        self.species = species
        self.typo = typo
        self.gender = gender
        self.origin = origin
        self.location_name = location_name
        self.episode = episode
        self.image_url = image_url
        self.created = created
        self.episode_n = episode_n

    def to_json(self):
        return {
            "_id": self._id,
            "name": self.name,
            "alive": self.alive,
            "species": self.species,
            "typo": self.typo,
            "gender": self.gender,
            "origin": self.origin,
            "location_name": self.location_name,
            "episode": self.episode,
            "image_url": self.image_url,
            "created": self.created,
            "episode_n": self.episode_n
        }

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from app.config import Config
from app.routes.character import personaje_router

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Bootstrap(app)
    
   
    app.register_blueprint(personaje_router)

    return app

app/routes/character.py
from flask import Blueprint, render_template,redirect,url_for,flash
from app.db import DabataseConnection
from app.models.character import Character
import requests

personaje_router = Blueprint('personaje_router', __name__)
db = DabataseConnection(5)

#LISTAR PERSONAJES 
@personaje_router.route('/')
def index():
    characters = db.collection.find().sort('_id', 1)
    return render_template('index.html', characters=characters)

#VER DETALLER PERSONAJES
@personaje_router.route('/profile/<id>')
def profile(id):
    id = int(id)
    data = db.collection.find_one({ '_id': id })
    return render_template('profile.html', personaje_data=data)


#ELIMINAR PRESONAJE
@personaje_router.route("/eliminar/<id>")
def delete_profile(id):
    id = int(id)
    #data = db.collection.find_one({ '_id': id })
    db.collection.delete_one({ '_id': id })
    flash("Personaje eliminado", "success")
    return redirect(url_for('personaje_router.index'))



#CARGAR PERSONAJES
@personaje_router.route('/load')
def cargar():
    for n in range(db.npags):
        r = requests.get(db.url + str(n+1))
        json = r.json()
        lista_jsons = json["results"]

        for element in lista_jsons:
            first_episode = element['episode'][0]
            ep = requests.get(first_episode)
            data = ep.json()
            first_episode = data['name']
            
            character = Character(
                _id=element['id'],
                name=element['name'],
                alive=element['status'],
                species=element['species'],
                typo=element['type'],
                gender=element['gender'],
                origin=element['origin']['name'],
                location_name=element['location']['name'],
                image_url=element['image'],
                episode=first_episode,
                created=element['created'],
                episode_n=element['episode']
            )
            db.collection.insert_one(character.to_json())
    
    return 'CARGA SUCCESS'

app/templates/base.html
{% extends "bootstrap/base.html" %} 

{% block body %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<h1 class="text-center text-primary"><b>Lista de Personajes de Rick y Morty</b></h1>
<hr>
{% block content %} {% endblock content %}
{% endblock body %}

app/templates/index.html
{% extends "base.html" %} {% block content %} {% for item in characters %} {#TRABAJA CON BOOSTRAP 5 border border-danger m-3#}
<div class="container ">
    <div class="row ">
        <div class="container ">
            <div class="panel text-center ">
                <div class="panel_body">
                    <div class="row bg-light">
                        <div class="col-6">
                            <center><img class="text-align" src="{{ item.image_url }}" alt=" centered {{ item.name }}" width="300" height="270">
                            </center>
                        </div>
                        <div class="col-6 ">
                            <h4>
                                <dt>Nombre:</dt>
                            </h4>
                            <h4>{{ item.name }}</h4>
                            <h4>
                                <dt>Alive:</dt> {{ item.alive }}
                            </h4>
                            <h4>
                                <dt>Especies:</dt> {{ item.species }}
                            </h4>
                            <h4>
                                <dt>Last known location:</dt> {{ item.location_name }}
                            </h4>
                            <h4>
                                <dt>First Seen in:</dt> {{ item.episode }}
                            </h4>

                            <a href="{{ url_for('personaje_router.profile', id=item._id)}}" class="btn btn-success  m-3">
                                <h4> Ver Perfil</h4>
                            </a>
                            <a href="{{ url_for('personaje_router.delete_profile', id=item._id)}}" class="btn btn-danger m-3">
                                <h4>Eliminar</h4>
                            </a>
                        </div>
                    </div>
                </div>


            </div>

        </div>
    </div>
</div>
{% endfor %} {% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% block content %}



<div class="container bg-light">
  <div class="row ">
    <div>
    </div>
    <div class="col-6">
      <img class="card-img-top" src={{personaje_data.image_url}} alt="">
    </div>
    <div class="col-6">
      <div class="card-body m-3">
          <h1 class="text-info display-1"><b>{{personaje_data.name}}</b></h1>
          <hr>
          <h2 >
            <b class="text-danger">Estatus:</b> {{personaje_data.alive}}
          </h2>
          <h2 >
            <b class="text-danger">Especies:</b> {{personaje_data.species}}
          </h2>
          <h2 >
            <b class="text-danger">Tipo:</b> {{ 'Alive' if personaje_data.typo else 'Dead' }}
          </h2>
          <h2 >
            <b class="text-danger">Género:</b> {{personaje_data.gender}}
          </h2>
          <h2 >
            <b class="text-danger">Origen:</b> {{personaje_data.origin}}
          </h2>
          <h2 >
            <b class="text-danger">Locación:</b> {{personaje_data.location_name}}
          </h2>
          <h2 >
            <b class="text-danger">Primer Episodio:</b> {{personaje_data.episode}}
          </h2>
          <h2 >
            <b class="text-danger">Episodios:</b> {{personaje_data.episode}}
          </h2>
          <h2 >
            <b class="text-danger">Numero de Episodios:</b> {{personaje_data.episode_n|length}}
          </h2>
          <h2 >
            <b class="text-danger">Creado en:</b> {{personaje_data.created}}
          </h2>
          
      </div>
      <div class="d-grid gap-2">
        <a href="{{url_for('personaje_router.index')}}" class="btn btn-primary m-3"><h2>Regresar a lista de personajes</h2></a>
      </div>
    </div>
  </div>
</div>
      
     
{% endblock %}